#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Stage {
    /// When the compiler encounters a module definition (e.g. `mod foo;`), it checks
    /// whether the corresponding file (e.g. `src/foo.sdg`) exists. If the file is
    /// found, the module enters this stage.
    Load,

    /// The compiler reads the source code as a string and converts it to a sequence
    /// of tokens.
    Lex,

    /// It creates an AST from the tokens.
    Parse,

    /// This stage performs per-file name resolution. It also does some lowerings
    /// that can be done per-file.
    /// Since this stage is processed per-file, it can run in parallel and can be
    /// cached for incremental compilation (you can reuse hir if the file hasn't
    /// changed).
    Hir,

    /// In this stage, the compiler performs name resolution across file
    /// boundaries. This stage requires all files' HIR to be loaded into memory
    /// simultaneously, so it cannot be parallelized.
    InterHir,

    /// It's a part of inter-hir that can run in parallel. I splitted the stages
    /// just to make it parallel.
    PostHir,

    /// MIR is like HIR, but a few more lowerings (that requires information from
    /// InterHir) are done. MIR is generated per-file, so it can be parallelized.
    /// But because it depends on InterHir, it cannot be cached like HIRs.
    ///
    /// After this, we're ready for type analysis.
    Mir,

    /// In this stage, the compiler performs type analysis, which includes both
    /// type inference and type checking. It also runs the poly-generic solver and
    /// performs monomorphization of generic types and functions.
    ///
    /// Since this stage needs all files' MIR to be available, it cannot be
    /// parallelized.
    InterMir,

    /// This stage handles lowering that requires type information.
    /// It lowers match expressions to decision trees. It also lowers `Field::Name`s
    /// to `Field::Index`.
    PostMir,

    /// Now that every lowering and checking are complete, it can do optimizations.
    /// It runs in parallel, but sometimes it needs items in other modules (e.g. when inlining).
    /// So, the compiler creates a global hash map for functions, and each worker reads/writes
    /// the hash map with locks.
    MirOptimize,

    /// The Bytecode stage converts the optimized MIR from a tree structure into a
    /// linear sequence of bytecode instructions for a stack machine.
    /// The generated bytecode can be either interpreted directly or further lowered
    /// to assembly or other target languages (WIP).
    ///
    /// This stage generates bytecodes per module, so it runs in parallel.
    ///
    /// This stage does not generate any errors or warnings.
    Bytecode,

    /// This stage does per-module bytecode optimization in parallel.
    BytecodeOptimize,

    /// Currently, only 1 backend is available: Backend::Bytecode.
    CodeGen,
}

pub const STAGES: [Stage; 13] = [
    Stage::Load,
    Stage::Lex,
    Stage::Parse,
    Stage::Hir,
    Stage::InterHir,
    Stage::PostHir,
    Stage::Mir,
    Stage::InterMir,
    Stage::PostMir,
    Stage::MirOptimize,
    Stage::Bytecode,
    Stage::BytecodeOptimize,
    Stage::CodeGen,
];

#[derive(Clone, Copy, Debug)]
pub enum Substage {
    // lex
    Lex,
    GroupTokens,
    ValidateSpans,

    // parse
    ParseSessionFromLexSession,
    Parse,
    CheckParse,

    // hir
    HirSessionFromParseSession,
    HirFromAst,
    SubstituteClosures,

    // inter-hir
    LoadHirModules,
    ResolveAliasLoop(usize),
    ResolveAssociatedItems,
    ResolvePoly,
    StoreInterHirLog,

    // inter-mir
    LoadMirModules,
    TypeSolveLoop(usize),
    InitSpanStringMap,
    StoreMonomorphizationInfo,
    DumpInterMirLog,
    PropagateMirUpdates,

    // code-gen
    LoadBytecodeModules,
    CodeGen,
}

impl Stage {
    pub fn is_parallel(&self) -> bool {
        match self {
            Stage::Load => true,
            Stage::Lex => true,
            Stage::Parse => true,
            Stage::Hir => true,
            Stage::InterHir => false,
            Stage::PostHir => true,
            Stage::Mir => true,
            Stage::InterMir => false,
            Stage::PostMir => true,
            Stage::MirOptimize => true,
            Stage::Bytecode => true,
            Stage::BytecodeOptimize => true,
            Stage::CodeGen => false,
        }
    }
}

impl Substage {
    pub fn render(&self) -> String {
        match self {
            Substage::Lex => String::from("lex"),
            Substage::GroupTokens => String::from("group_tokens"),
            Substage::ValidateSpans => String::from("validate_spans"),
            Substage::ParseSessionFromLexSession => String::from("parse_session_from_lex_session"),
            Substage::Parse => String::from("parse"),
            Substage::CheckParse => String::from("check_parse"),
            Substage::HirSessionFromParseSession => String::from("hir_session_from_parse_session"),
            Substage::HirFromAst => String::from("hir_from_ast"),
            Substage::SubstituteClosures => String::from("substitute_closures"),
            Substage::LoadHirModules => String::from("load_hir_modules"),
            Substage::ResolveAliasLoop(i) => format!("resolve_alias_loop_{i}"),
            Substage::ResolveAssociatedItems => String::from("resolve_associated_items"),
            Substage::ResolvePoly => String::from("resolve_poly"),
            Substage::StoreInterHirLog => String::from("store_inter_hir_log"),
            Substage::LoadMirModules => String::from("load_mir_modules"),
            Substage::TypeSolveLoop(i) => format!("type_solve_loop_{i}"),
            Substage::InitSpanStringMap => String::from("init_span_string_map"),
            Substage::StoreMonomorphizationInfo => String::from("store_monomorphization_info"),
            Substage::DumpInterMirLog => String::from("dump_inter_mir_log"),
            Substage::PropagateMirUpdates => String::from("propagate_mir_updates"),
            Substage::LoadBytecodeModules => String::from("load_bytecode_modules"),
            Substage::CodeGen => String::from("code_gen"),
        }
    }
}
