[package]
name = "sodigy-span"
version = "0.1.0"
edition = "2024"

[dependencies]
sodigy-endec = { version = "0.1.0", path = "../endec" }
sodigy-file = { version = "0.1.0", path = "../file" }
sodigy-string = { version = "0.1.0", path = "../string" }
