[package]
name = "sdg_interpret"
version = "0.1.0"
edition = "2021"

[dependencies]
sdg_ast = { path = "../sdg_ast", version = "*" }
sdg_inter_mod = { path = "../sdg_inter_mod", version = "*" }
sdg_uid = { path = "../sdg_uid", version = "*" }
