use crate::ErrorToken;
use sodigy_name_analysis::NameKind;
use sodigy_string::InternedString;
use sodigy_token::InfixOp;

mod render;

#[derive(Clone, Debug)]
pub enum ErrorKind {
    InvalidNumberLiteral,
    InvalidStringLiteralPrefix,
    InvalidCharacterInIdentifier(char),
    WrongNumberOfQuotesInRawStringLiteral,
    UnterminatedStringLiteral,
    InvalidCharLiteral,
    InvalidCharLiteralPrefix,
    UnterminatedCharLiteral,
    InvalidByteLiteral,
    InvalidEscape,
    EmptyCharLiteral,
    UnterminatedBlockComment,
    InvalidUtf8,
    InvalidUnicodeCharacter,
    InvalidUnicodeEscape,
    UnmatchedGroup {
        expected: u8,
        got: u8,
    },

    // You can use up to 127 quotes for opening or 254 quotes (open 127 + close 127) consecutively.
    TooManyQuotes,
    UnclosedDelimiter(u8),
    UnexpectedToken {
        expected: ErrorToken,
        got: ErrorToken,
    },
    UnexpectedEof {
        expected: ErrorToken,
    },
    // It's like Eof, but an end of a group (parenthesis, braces or brackets).
    UnexpectedEog {
        expected: ErrorToken,
    },
    DocCommentForNothing,
    DocCommentNotAllowed,
    DecoratorNotAllowed,
    CannotBePublic,
    BlockWithoutValue,
    StructWithoutField,
    EmptyCurlyBraceBlock,
    PositionalArgAfterKeywordArg,
    NonDefaultValueAfterDefaultValue,
    CannotDeclareInlineModule,
    InclusiveRangeWithNoEnd,
    AstPatternTypeError,  // TODO: more context?
    DifferentNameBindingsInOrPattern,
    InvalidFnType,
    EmptyMatchStatement,
    RedundantDecorator(InternedString),

    // TODO: suggest similar names
    // TODO: tell what it's trying to decorator
    InvalidDecorator(InternedString),

    // Syntax errors in patterns
    CannotBindNameToAnotherName(InternedString),
    CannotAnnotateType,
    RedundantNameBinding(InternedString, InternedString),

    NameCollision {
        name: InternedString,

        // TODO
        // context: NameCollisionContext,
    },
    CyclicLet {
        names: Vec<InternedString>,
    },
    CyclicAlias {
        names: Vec<InternedString>,
    },

    // TODO: suggest similar names
    UndefinedName(InternedString),

    KeywordArgumentRepeated(InternedString),
    KeywordArgumentNotAllowed,
    AliasResolveRecursionLimitReached,

    // TODO: suggest similar names
    InvalidKeywordArgument(InternedString),

    // TODO: We need more helpful error variants
    //       e.g. if we know the types, we can guess which argument is missing, or surplus, or in different order
    MissingArgument {
        expected: usize,
        got: usize,
    },
    UnexpectedArgument {
        expected: usize,
        got: usize,
    },

    StructFieldRepeated(InternedString),
    MissingStructField(InternedString),

    // TODO: suggest similar name
    InvalidStructField(InternedString),

    DependentTypeNotAllowed,

    // These type errors are generated by `mir-type` crate, and the crate uses its own data types
    // to represent types. But this crate cannot depend on `mir-type`, so those are types are
    // converted to string.
    UnexpectedType {
        expected: String,
        got: String,
    },
    CannotInferType {
        id: Option<InternedString>,
    },
    PartiallyInferedType {
        id: Option<InternedString>,
        r#type: String,
    },
    CannotInferGenericType {
        id: Option<String>,
    },
    PartiallyInferedGenericType {
        id: Option<String>,
        r#type: String,
    },
    CannotApplyInfixOp {
        op: InfixOp,
        arg_types: Vec<String>,
    },
    MultipleModuleFiles {
        module: String,
    },
    ModuleFileNotFound {
        module: String,
    },

    // --- warnings from here ---
    UnusedName {
        name: InternedString,
        kind: NameKind,
    },
}
