[package]
name = "sdg_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
hmath = "*"
sdg_endec = { path = "../sdg_endec", version = "*" }
sdg_fs = { path = "../sdg_fs", version = "*" }
sdg_hash = { path = "../sdg_hash", version = "*" }
sdg_uid = { path = "../sdg_uid", version = "*" }
